services:
  mysql:
    image: mysql:8.0
    container_name: wbs_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wbs
      MYSQL_USER: wbsuser
      MYSQL_PASSWORD: wbspass
    ports:
      - "3359:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql